### ISSUE TITLE
[Product] Clarity on tracking course completion

### ISSUE THREAD

**Issue by karntrehan** [COMPASS-DPG/docs#4]
We need to finalise tracking of course completion. This will impact how we define the tech structure of marketplace. 

Should it be manual?
Should it be API driven? 
Should it be beckn compliant?

**Comment by MohitNSamagra** [comment]
It'll be API driven. As for the incentive we were thinking of adding clauses in an agreement for now. Still thinking more around this. WIll get back.

**Comment by karntrehan** [comment]
Entry points: 

1. Show completed courses
2. Submit rating to completed courses.
3. Show course by clicking notification.

APIs to be exposed: 
1. Courses by competency
2. Courses by level.

Recommendation engine logic: 
1. @MohitNSamagra and @rohitsamagra to come back on after talking to tarento.

**Comment by karntrehan** [comment]
Course completion to be triggered by the 3CP. 

We will define the flow for Sunbird Lern completion with the lowest barrier approach.
